### ISSUE TITLE
启动器内部更新启动器不能打开了

### ISSUE THREAD

**Issue by wjyj-Sikong** [HoraceHuang-ui/MiHOYO-MiXED-Launcher#23]
今天我进启动器然后更新启动器，更新结束后就打不开了，我看进程里面打开的时候有两个进程，然后没一会就自动关闭了

**Comment by HoraceHuang-ui** [comment]
我刚才试了一下重新安装release里2.3.3版本然后再按正常流程安装2.4.0，没有遇到错误哎……请问打不开是指程序主窗口也没有弹出吗？试一下把那两个进程都强制停止然后再安装呢？

**Comment by HoraceHuang-ui** [comment]
Can't repro，暂时关闭issue
