### ISSUE TITLE
账户信息加载失败

### ISSUE THREAD

**Issue by dayumsista** [HoraceHuang-ui/MiHOYO-MiXED-Launcher#26]
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/147481512/11933561-0927-4e22-a0e9-2453dd0d9449)

**Comment by dayumsista** [comment]
这个就是没开 那个 角色详情 导致的吗

**Comment by HoraceHuang-ui** [comment]
确实没打开角色展柜哦，但是按理说我这边设计的不是这么个反应，你可以先让他不急着打开噢，我晚点排查一下
![Screenshot_20231106-113543.png](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/67905897/87fb7a15-e892-429f-a7dc-e1014d6e44dc)

**Comment by HoraceHuang-ui** [comment]
我刚试了是正常没有问题的，你可以再查询一次试试？可能是API炸了
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/67905897/074f0d96-7b43-4a22-95ac-a2205c7ff810)

**Comment by HoraceHuang-ui** [comment]
Can't repro，暂时关闭issue
