### ISSUE TITLE
[Help] Crowdin我真的不会用

### ISSUE THREAD

**Issue by MCheping8108** [HoraceHuang-ui/MiHOYO-MiXED-Launcher#28]
我在Crowdin翻译了法语，打算在Crowdin上传到你的翻译项目，但是我找不到在哪里可以上传，你这里有什么更简便的方法吗？

**Comment by HoraceHuang-ui** [comment]
感谢老哥贡献！之前找不到法语翻译选项是因为我没有在Crowdin的目标语言中勾选法语，现在你再访问Crowdin就可以看到法语翻译的选项啦！可以直接在`Translations` -> `Upload existing translations`中上传你本地的json文件进行快速导入噢！
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/67905897/5dc8caa6-e591-459d-8171-c9f3629cb71b)

**Comment by MCheping8108** [comment]
[cid:a2dbab6a-5859-4c67-88b6-648387a8ffde]
我已经上传到了你的项目
________________________________
发件人: Yiyu Huang ***@***.***>
发送时间: 2023年11月19日 12:35
收件人: HoraceHuang-ui/MiHOYO-MiXED-Launcher ***@***.***>
抄送: 和平peaceful ***@***.***>; Author ***@***.***>
主题: Re: [HoraceHuang-ui/MiHOYO-MiXED-Launcher] [Help] Crowdin我真的不会用 (Issue #28)


感谢老哥贡献！之前找不到法语翻译选项是因为我没有在Crowdin的目标语言中勾选法语，现在你再访问Crowdin就可以看到法语翻译的选项啦！可以直接在Translations -> Upload existing translations中上传你本地的json文件进行快速导入噢！
[image]<https://user-images.githubusercontent.com/67905897/284037147-5dc8caa6-e591-459d-8171-c9f3629cb71b.png>

―

**Comment by HoraceHuang-ui** [comment]
收到啦~看起来Crowdin似乎错误地将你上传的文件中未翻译的部分也当作已翻译了，我已将它们全部还原，目前法语的实际翻译进度是47%噢
