### ISSUE TITLE
[Feature Request] 大屏幕模式

### ISSUE THREAD

**Issue by fred913** [HoraceHuang-ui/MiHOYO-MiXED-Launcher#4]
类似新版Steam的大屏幕模式，为启动器用户提供一个类似主机的体验，同时让右上角的绿色全屏按钮不要卵用没有。（语文0分（x
### To-Do
- [x] 全屏模式UI
- [x] 手柄操作支持

**Comment by HoraceHuang-ui** [comment]
- 红绿灯还挺搞笑的，我本来是想把绿灯做成灰色的，但又感觉这样不好看，最后还是决定留着但不响应任何操作了（
- 针对全屏模式，会抽时间考虑适配，尽量本学期内搞定（如果学校里事情不多的话qwq）
- 针对手柄操作支持，由于此前未做了解，故近期暂没有能力适配（refer to [gamepad API](https://developer.mozilla.org/zh-CN/docs/Web/API/Gamepad_API/Using_the_Gamepad_API)）

**Comment by fred913** [comment]
我尝试一下叭 非常感谢

**Comment by fred913** [comment]
@HoraceHuang-ui 最近在大屏幕模式方面取得了一些进展，您这边能否留个联系方式（不便公开可以发到我readme留的的email）？后续可以交流一下，我把当前版本的一些必要的启动器功能在大屏幕demo里实现。

**Comment by HoraceHuang-ui** [comment]
大屏幕模式正在做了（还未完工）Commit [03251c4](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/commit/03251c485540a84447ee25d1128b1d4b3f45cb0e)

**Comment by HoraceHuang-ui** [comment]
大屏模式已完工并Release，手柄模式正在做了

**Comment by HoraceHuang-ui** [comment]
手柄模式已完成适配，欢迎试用！🥳
