### ISSUE TITLE
[Help] the title of help wanted report

### ISSUE THREAD

**Issue by dayumsista** [HoraceHuang-ui/MiHOYO-MiXED-Launcher#5]
容我问个傻逼问题
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/147481512/5d3aaf4f-1a0a-4159-a2b8-ae1326184a82)
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/147481512/d1d97309-df03-4ffd-ac37-58578b30bdfb)
哪个才是我该填入的根目录

**Comment by HoraceHuang-ui** [comment]
哈喽老哥，感谢使用！目前程序设计的逻辑是游戏本体的目录在启动器的目录里面，即用官方启动器安装游戏时的默认结构：
```
| 根目录
    | - Games
        | - BH3.exe
    | - launcher.exe
```
暂时没有考虑到启动器和游戏本体分开的情况噢！想要正常使用启动游戏功能的话，可以在launcher.exe所在的目录，创建一个`Games`文件夹，然后把游戏本体挪进去，形成一个上面给出的文件结构，并在我的启动器里以launcher.exe所在的这一层作为根目录导入哦！

很抱歉给你带来困扰，其实这个问题很久之前是有考虑过，后来想着先把其他重点功能实现，加上身边的人都是直接用上述文件结构的，最近开学了忙于学业、竞赛和启动器的多语言适配，就给整忘了😭会提上日程的！

**Comment by dayumsista** [comment]
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/147481512/7405b10b-71e2-49f6-a620-3c0d79933eb8)
还有个问题就是  这里我导入了个原神的uid 但是啥也没有 ![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/147481512/167d7c15-f4de-420c-81fa-63c91debb6b6)

此外 启动路径可以直接去选择Game路径下的BH3.exe的吧 那样也能直接启动游戏

**Comment by HoraceHuang-ui** [comment]
1. 啊？请问可以提供一下UID嘛？
2. 是的，你可以直接选择`导入的路径\Games\BH3.exe`来直接启动游戏，但注意这样就无法从程序内打开官方启动器了噢！等我做完启动器和游戏本体分别导入后会关闭这个Issue

**Comment by dayumsista** [comment]
237255062 UID
同学的 
我自己不玩原神所以没有uid hhh

**Comment by HoraceHuang-ui** [comment]
找到问题啦，是我使用的API在返回的数据中，在角色没有衣装的时候“头像”那一栏有时候不包含`costumes`（角色衣装）有时候又包含一个空的`costumes`导致的。由于我的账号头像是带衣装，用于测试的几个朋友的账号返回的内容都不含`costumes`，因此检测条件就有点片面 :(
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/67905897/b2c5bee6-7797-4c40-84e9-0824237c2bdd)
另外，你的这位同学没有在游戏中打开展示角色详情，所以这里是查询不了角色信息的哦

**Comment by HoraceHuang-ui** [comment]
问题1已在 [8db22f](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/commit/8db22fb185d343a817328cefa30dd77036666e16) 中修复

**Comment by HoraceHuang-ui** [comment]
哥们还是接着开着吧，问题2还没解决呢，issue开着就当是时刻提醒开摆的我了 T_T

**Comment by dayumsista** [comment]
樂
修复了问题1之后是不是release要重新打包一下
感觉那个安装程序不像是能在线修复的（

**Comment by HoraceHuang-ui** [comment]
是的，等到我写完整个软件的国际化之后会一起打包，这样估计至少等一周起步了……你可以直接从上面那个Commit中获取GitHub Actions生成的文件，下下来解压之后只要开安装程序就行了，别的那些乱七八糟的文件可以删掉

**Comment by dayumsista** [comment]
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/147481512/303eca92-e5f3-44a2-a6c4-8e8f1bda294c)
移动文件 目录也写的D:\BH3
但是还是启动不了

**Comment by HoraceHuang-ui** [comment]
应该命名为Game`s`，程序里导入的路径是`D:\BH3`哦，代码如下，程序打开的就是`D:\BH3\Games\BH3.exe`，应该就正常啦
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/67905897/98fc969b-b1ab-4b56-a72e-5aa21b590e2b)

**Comment by dayumsista** [comment]
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/147481512/a808a6eb-4e6f-48f6-886b-7c034f2b2ad3)
今天启动的时候不知道为什么显示的是英文版本
崩3的Info Actovity还有Announce都一样 啥都加载不出来 图也是6.9的
崩坏和星铁的Info Activity Announce能正常加载
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/147481512/cc78d50d-e0f5-4c30-9c4f-897dbafdaa0c)

**Comment by HoraceHuang-ui** [comment]
因为我为了测试方便，在App.vue的onMounted最后一行加了一个切换英文的代码，把它改成zh-CN再重新运行两次就是中文啦。崩3国际版的官方启动器也是一片空白的，因为api只返回了一张背景图片。

**Comment by HoraceHuang-ui** [comment]
1. 关于游戏本体和启动器不在同一目录问题，重新做了导入路径的逻辑，现在可以选择是否要分开导入了；刚做完崩3的，等把三个游戏都弄完就commit。
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/67905897/b6a9a553-8aa5-40f9-8f12-700442adb33f)
2. 做了设置页面，现在可以在里面调语言了。（已提交 [3af8111](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/commit/3af8111e62ba37597c84af1b1c58158f05c09426)）
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/67905897/f16b9a71-6241-46ce-ac27-1156efc61d54)
3. 关于部分游戏的部分语言在部分时段存在部分字段返回数据为空的问题，在修了在修了（新建文件夹）

待全部修复后关闭Issue。

**Comment by HoraceHuang-ui** [comment]
已全部解决，结束战斗 ;)

**Comment by dayumsista** [comment]
![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/147481512/7f212847-dbaa-4e6f-8960-136fbfe5a67a)
图片裂了捏

**Comment by HoraceHuang-ui** [comment]
这是因为星铁的角色分析用的是GitHub域名，所以需要翻墙噢

**Comment by dayumsista** [comment]
是每次开都要使吗 还是第一次用的时候开梯子把图像缓存到本地

**Comment by HoraceHuang-ui** [comment]
每次都要的，电脑上梯子平时都是24小时挂着的吧

**Comment by dayumsista** [comment]
分享给不会挂梯子的女同学（
