### ISSUE TITLE
[Feature request] 自己做了个工具箱页面

### ISSUE THREAD

**Issue by MCheping8108** [HoraceHuang-ui/MiHOYO-MiXED-Launcher#52]
# 是否在更新计划中

## 我自己做了个工具箱页面，可以点击选项打开浏览器
![PixPin_2024-02-14_11-17-33](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/102772286/49b82c00-7612-4ad9-8295-c8fd31b236f4)

**Comment by HoraceHuang-ui** [comment]
##
感谢老哥的想法！但是由于这些网站我个人不是很经常用得到，且随着后续内容的增多不太好排布，我觉得不需要再单开一个页面了，而是像这样在每个游戏页面的右上角单独嵌一条竖的比较好哦！图标风格就做成类似官方启动器那样。

![image](https://github.com/HoraceHuang-ui/MiHOYO-MiXED-Launcher/assets/67905897/a54bf376-2fbc-40bc-a28f-f30d92e5baba)
---
另外我看了下你实现的代码，其实可重用性不太高。要实现以上我的想法，可以弄一个`GameTools.vue`组件，`props`接收`{title, desc, url, icon}`对象的数组，在里面用v-for渲染，再在游戏页面中使用
```
<GameTools :icons="对象数组" class="absolute right-0 top-0 ..." .../>
````

**Comment by HoraceHuang-ui** [comment]
关于图标的话，考虑到日益发福的应用体积，能用bootstrap尽量用，尽量避免导入静态图片资源哦！

**Comment by MCheping8108** [comment]
好的，晚上我会想办法，你可以选择关闭此issues

**Comment by HoraceHuang-ui** [comment]
嗯嗯那我先关闭咯，我正在外面旅游初八才回来，到时写个ui看看效果再斟酌斟酌
