### ISSUE TITLE
关于手柄操作

### ISSUE THREAD

**Issue by MaoXiangling** [HoraceHuang-ui/MiHOYO-MiXED-Launcher#60]
#### 建议接入 node-hid 库来适配一些手柄设备

**Comment by HoraceHuang-ui** [comment]
node-hid库成本太高，要做手柄适配还是用JS自带的GamepadAPI。目前我有另外两个前端项目在做（实习的跟学校的🥲），近期没时间跟进，等空闲了再跟进哦！

**Comment by HoraceHuang-ui** [comment]
正在做了哦，计划是放一些关键功能在一个单独的界面里

**Comment by HoraceHuang-ui** [comment]
手柄模式已完成适配，release已发布，欢迎试用！🥳
