### ISSUE TITLE
[Feature request] 单独一个崩坏3游戏程序启动

### ISSUE THREAD

**Issue by dayumsista** [HoraceHuang-ui/MiHOYO-MiXED-Launcher#85]
以此链接获得的崩坏3游戏全数据包下载链接 解压出来并不包括启动器部分
https://bh3-launcher-static.mihoyo.com/bh3_cn/mdk/launcher/api/resource?channel_id=1&key=SyvuPnqL&launcher_id=4&sub_channel_id=1
在使用的时候单独一个BH3.exe 不具备Launcher无法以非默认结构进行使用

此外 上面这个链接如果可以 兴许可以整合进启动器内 反正崩坏3现在也没有差分包

**Comment by HoraceHuang-ui** [comment]
其实针对这个问题的话，你就只导入游戏本体的路径，然后启动器那一栏随便选个路径把程序骗过去就可以了（

最近在找实习和校内项目很忙，涉及到启动器内直接一站式实现官方下载和更新功能的会直接大改代码，暂无计划哦
